config/routes.rb
  Rails.application.routes.draw do
  get 'passwords/edit'
  get 'passwords/update'
  root 'sessions#index'

  # resources :sessions
  resources :posts

  get "/home", to: "posts#home"
  # get "/login", to: "logins#new"
  # post "/check_login", to: "logins#check_login"

  get 'sign_up', to: 'sessions#new'
  post 'sign_up', to: 'sessions#create'
  get 'sign_in', to: 'logins#new'
  post 'sign_in', to: 'logins#create', as: 'log_in'
  get 'logout', to: 'logins#destroy'
  get 'password',  to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit', as: 'reset_password'
  patch 'password/reset/edit', to: 'password_resets#update'



  # root 'posts#home'  
  # get 'posts/home'
  # get 'posts/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 3, maximum: 10 }
	validates :description, presence: true, length: { minimum: 10, maximum: 50 }
	validates :reaction, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name,:last_name, presence: true, length: { minimum: 4, maximum: 20 }
	validates :email, presence: true, uniqueness: true,
	format:  { with: /\A[^@\s]+@[^@\s]+\z/, message: 'entered is invalid' }
	validates :gender, presence: true
	validates :phone_number, presence: true, :numericality => true,length: { minimum: 10, maximum: 10 }
	validates :password,:confirm_password, presence: true, length: { minimum: 4, maximum: 10 }	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user

	def set_current_user
		Current.user =  User.find_by(id: session[:user_id]) if session[:user_id]
	end

	def require_user_logged_in!
		redirect_to sign_in_path, flash[:notice] ="You must be signed in" if Current.user.nil?
	end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new
		if Current.user
			flash[:notice] = "User is already logged in!"
		  	redirect_to home_path
		else
			@user = User.new	
		end

	end

	def create
		 @user = User.find_by(email: params[:user][:email])
		 # byebug

	    if @user.present? && @user.password == params[:user][:password]
	      flash[:notice] = "User has successfully logged in"
	      session[:user_id] = @user.id
	      redirect_to '/home'
	    else
	       @user = User.new		
	      flash[:notice] = "Invalid credentials entered"
	      render 'new'
	    end  
	end
	def destroy
		session[:user_id] = nil 
		flash[:notice] ="User is logged out"
		redirect_to root_path

	end
end
	

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	def new		
	end
	def edit
		@user = User.find_signed!(params[:token], purpose: 'password_reset')
		rescue ActiveSupport::MessageVerifier::InvalidSignature
		redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
	end

	def update
		@user = User.find_signed!(params[:token], purpose: 'password_reset')
		if @user.update(password_params)
			redirect_to sign_in_path, flash[:notice] = "Password is successfully reset. Please sign in."
		else
			render 'edit'
		end
	end

	private
	def password_params
		params.require(:user).permit(:password,:confirm_password)
	end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update

    if Current.user.update(password_params)      
      redirect_to log_in_path
      flash[:notice] ="User password successfully updated"
    else
      flash[:notice] ="Password entered is not updated"
      render 'edit'
    end
  end

  private
  def password_params
    params.require(:user).permit(:password,:confirm_password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def home
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new 
  end

  def create
     @post = Post.new(post_params)

     if @post.save
        flash[:notice] = "Post has been successfully created"
        redirect_to @post
     else
        render 'new'
     end
  end

  def edit
    @post = Post.find(params[:id])    
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = "Post has been successfully updated"
      redirect_to home_path
    else
      render 'edit'
    end    
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy(post_params)
      flash[:notice] = "Post has been successfully deleted"
      redirect_to home_path
    else
      render 'edit'
    end    
    
  end

  private
  def post_params()
    params.require(:post).permit(:title,:description,:reaction)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if Current.user
			flash[:notice] = "User is already logged in!"
		  	redirect_to home_path
		else
			@user = User.new	
		end
	end
	
	def create
		@user = User.new(user_params)
	
		if @user.password == @user.confirm_password && @user.save 
	        flash[:notice] = "User successfully created"
	        # session[:user_id] = @user.id
	        redirect_to '/sign_in'
     	else
     		if @user.password != @user.confirm_password
     			flash[:notice] = "Entered password does not match"
     		else
     			flash[:notice] = "Details are not correctly filled"
     		end
        	render 'new'
     	end
	end

	private
	  def user_params()
	    params.require(:user).permit(:first_name,:last_name,:email,:phone_number,:gender,:password,:confirm_password)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <%= link_to 'Sites ', root_path, class: "navbar-brand" %>
  
  <ul class="navbar-nav">
    <% if Current.user %>
      <strong style="color:white;"> Logged in as <%= Current.user.email %></strong>
      <li class="nav-item topnav-right">
        <%= link_to 'Edit Password', edit_password_path,class: "nav-link" %>
      </li>
      <li class="nav-item topnav-right">
          <%# form_with %>
          <%= link_to 'Logout ',logout_path, method: :delete, class: "nav-link" %>
          <%# <%= form.submit%> 
          <%# end %>
      </li>
    <% else %>
      <li class="nav-item topnav-right">  
        <%= link_to 'Sign In', sign_in_path , class: "nav-link"%>
        
      </li>
      <li class="nav-item topnav-right">
        <%= link_to 'Sign Up', sign_up_path, class: "nav-link " %>  
        </li>
      <li class="nav-item topnav-right">
        <%= link_to 'Reset Password', reset_password_path, class: "nav-link"%>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sites</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show"><%= flash[:notice] %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/logins/_form.html.erb
<div class="form-group">
  <%= form_with model: @user, url: sign_in_path,local: true do |form| %>   
    <p>
      <strong><%= form.label :email %><br></strong>
      <%= form.text_field :email,:class => "form-control"%>
      <% if @user.errors.any? %>
      <div id="error_explanation" >
        <ul class="field_with_errors">
          <% @user.errors.full_messages_for(:email).each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    </p>
    <p>
      <strong><%= form.label :password %><br></strong>
      <%= form.password_field :password,:class => "form-control"%>
      <% if @user.errors.any? %>
        <div id="error_explanation" >
          <ul class="field_with_errors">
            <% @user.errors.full_messages_for(:password).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <br>
      <%= form.submit value="Login"%>
    </p>   
  <% end %>
</div>

app/views/logins/new.html.erb
	<%= image_tag("image5.jpg", alt: 'Description', :size => "1108x180")%>
	<div class="jumbotron text-center">
		 <h1>Login Page</h1>
 	</div>
 	<%= render 'form' %>
 	
 	
 	

app/views/posts/_form.html.erb
<div class="form-group">
  <%= form_with model: @post, local: true do |form| %>   
    <p>
      <strong><%= form.label :title %><br></strong>
      <%= form.text_field :title,:class => "form-control" %>
      <% if @post.errors.any? %>
      <div id="error_explanation" >
        <ul class="field_with_errors">
          <% @post.errors.full_messages_for(:title).each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    </p>
   
    <p>
      <strong><%= form.label :description %><br></strong>
      <%= form.text_area :description,:class => "form-control"%>
      <% if @post.errors.any? %>
      <div id="error_explanation" >
        <ul class="field_with_errors">
          <% @post.errors.full_messages_for(:description).each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    </p>

     <p>
      <strong><%= form.label :reaction %><br></strong>
      <%= form.text_field :reaction,:class => "form-control"%>
      <% if @post.errors.any? %>
        <div id="error_explanation" >
          <ul class="field_with_errors">
            <% @post.errors.full_messages_for(:reaction).each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </p>
   
    <p>
      <%= form.submit%>
    </p>   
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= image_tag "image5.jpg", alt: 'desc', :size => "1108x180"%>
<div class="jumbotron text-center">
	 <h1>Edit Post Page</h1>
</div>

 <%= render 'form' %>

 <%#= link_to 'Back', home_path,:class => "btn btn-info" %>

app/views/posts/home.html.erb
  <%= image_tag("image6.jpg", alt: 'Description', :size => "1108x180")%>
  <h1 class="jumbotron text-center" style="background-image: url('image6.jpg'); background-size: 100% 100%;">Welcome to Sites World!!!</h1>
  
  <%= link_to 'New Post', new_post_path,:class => "btn btn-info" %>
  <br>
  <br>
  <table class="table table-dark table-striped">
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Reaction</th>
      <th colspan="3">Action List</th>
    </tr>
   
    <% @posts.each do |post| %>
      <tr>
        <td><strong><%= post.title %></strong></td>
        <td><%= post.description %></td>
        <td><%= post.reaction %></td>
        <td><%= link_to 'Show', post_path(post),:class => "btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_post_path(post),:class => "btn btn-info"%></td>
        <td><%= link_to 'Destroy', post_path(post),
                method: :delete,
                data: { confirm: 'Are you sure?' },:class => "btn btn-info" %>                
            <%# <%= button_to 'Sign Out', post_path(post), method: :delete %>
            <%# <%= link_to 'Sign Out111', post_path(post), data: {turbo_method: :delete} %>
        </td>
      </tr>
    <% end %>
  </table>

  <footer class="footer fixed-bottom text-center">
    @copyright: iknir
  </footer>

app/views/posts/new.html.erb
	<%= image_tag("image5.jpg", alt: 'Description', :size => "1108x180")%>
	<div class="jumbotron text-center">
		 <h1>New Post Page</h1>
 	</div>
 	<%= render 'form' %>
 	<%# <%= link_to 'Back', home_path, :class => "btn btn-info" %>
 

app/views/posts/show.html.erb
	<%= image_tag("image5.jpg", alt: 'Description', :size => "1108x180")%>
	<div class="jumbotron text-center">
		<h1>Post in Focus</h1>
	</div>
	<table class="table table-dark table-striped">
		<tr>
			<th colspan="2", class="text-center">Post Details</th>
		</tr>
		<tr>
			<td><strong> Title:</strong></td>
			<td><%=  @post.title %></td>
		</tr>
		<tr>
			<td><strong> Description:</strong></td>
			<td><%=  @post.description %></td>
		</tr>
		<tr>
			<td><strong> Reaction:</strong></td>
			<td><%=  @post.reaction %></td>
		</tr>	
	</table>

 <%#= link_to 'Back', home_path, :class => "btn btn-info" %></td> 